using FluentValidation;
using SamplVSSkill.Domain.Entities;
using SamplVSSkill.Infrastructure.Persistence;

namespace SamplVSSkill.Features.Specialties.CreateSpecialty;

// ── Request / Response ──────────────────────────────────────────
public record CreateSpecialtyCommand(string Name);
public record CreateSpecialtyResponse(int Id, string Name, bool IsActive, DateTime CreatedAt);

// ── Validator ───────────────────────────────────────────────────
public class CreateSpecialtyValidator : AbstractValidator<CreateSpecialtyCommand>
{
    public CreateSpecialtyValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty().WithMessage("El nombre de la especialidad es requerido.")
            .MaximumLength(100).WithMessage("El nombre no puede exceder 100 caracteres.");
    }
}

// ── Command Handler (EF Core) ───────────────────────────────────
public class CreateSpecialtyCommandHandler
{
    private readonly AppDbContext _db;

    public CreateSpecialtyCommandHandler(AppDbContext db) => _db = db;

    public async Task<CreateSpecialtyResponse> HandleAsync(
        CreateSpecialtyCommand command, CancellationToken ct)
    {
        var specialty = new Specialty
        {
            Name      = command.Name,
            IsActive  = true,
            CreatedAt = DateTime.UtcNow
            // Id is auto-generated by the DB (serial)
        };

        _db.Specialties.Add(specialty);
        await _db.SaveChangesAsync(ct);

        return new CreateSpecialtyResponse(
            specialty.Id, specialty.Name, specialty.IsActive, specialty.CreatedAt);
    }
}
