using FluentValidation;
using SamplVSSkill.Domain.Entities;
using SamplVSSkill.Infrastructure.Persistence;

namespace SamplVSSkill.Features.CenterTypes.CreateCenterType;

// ── Request / Response ──────────────────────────────────────────
public record CreateCenterTypeCommand(string Name);
public record CreateCenterTypeResponse(int Id, string Name, bool IsActive, DateTime CreatedAt, DateTime UpdatedAt);

// ── Validator ───────────────────────────────────────────────────
public class CreateCenterTypeValidator : AbstractValidator<CreateCenterTypeCommand>
{
    public CreateCenterTypeValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty().WithMessage("El nombre del tipo es requerido.")
            .MaximumLength(100).WithMessage("El nombre no puede exceder 100 caracteres.");
    }
}

// ── Command Handler (EF Core) ───────────────────────────────────
public class CreateCenterTypeCommandHandler
{
    private readonly AppDbContext _db;

    public CreateCenterTypeCommandHandler(AppDbContext db) => _db = db;

    public async Task<CreateCenterTypeResponse> HandleAsync(
        CreateCenterTypeCommand command, CancellationToken ct)
    {
        var now = DateTime.UtcNow;
        var centerType = new CenterType
        {
            Name      = command.Name,
            IsActive  = true,
            CreatedAt = now,
            UpdatedAt = now
            // Id auto-generated by DB (identity)
        };

        _db.CenterTypes.Add(centerType);
        await _db.SaveChangesAsync(ct);

        return new CreateCenterTypeResponse(
            centerType.Id, centerType.Name, centerType.IsActive,
            centerType.CreatedAt, centerType.UpdatedAt);
    }
}
